package org.jmanderson.subbing.hibernate;



/**
 * AbstractHolidays generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractHolidays  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Integer year;
     private Integer month;
     private Integer day;
     private String description;


    // Constructors

    /** default constructor */
    public AbstractHolidays() {
    }

    
    /** full constructor */
    public AbstractHolidays(Integer year, Integer month, Integer day, String description) {
        this.year = year;
        this.month = month;
        this.day = day;
        this.description = description;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }

    public Integer getMonth() {
        return this.month;
    }
    
    public void setMonth(Integer month) {
        this.month = month;
    }

    public Integer getDay() {
        return this.day;
    }
    
    public void setDay(Integer day) {
        this.day = day;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
   








}