/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Sep 09 17:41:27 EDT 2005 by MyEclipse Hibernate Tool.
 */
package org.jmanderson.subbing.hibernate;

import java.io.Serializable;

/**
 * A class that represents a row in the organists table. 
 * You can customize the behavior of this class by editing the class, {@link Organists()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractOrganists 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.String username;

    /** The value of the emailSet one-to-many association. */
    private java.util.Set emailSet;

    /** The value of the phoneSet one-to-many association. */
    private java.util.Set phoneSet;

    /** The value of the schedulesSet one-to-many association. */
    private java.util.Set schedulesSet;

    /** The value of the simple nickname property. */
    private java.lang.String nickname;

    /** The value of the simple fullname property. */
    private java.lang.String fullname;

    /** The value of the simple details property. */
    private java.lang.String details;

    /** The value of the simple availsat property. */
    private java.lang.Boolean availsat;

    /** The value of the simple availsun property. */
    private java.lang.Boolean availsun;

    /** The value of the simple travel property. */
    private java.lang.String travel;

    /** The value of the simple wedfun property. */
    private java.lang.String wedfun;

    /** The value of the simple available property. */
    private java.lang.Boolean available;
    
    /** The value of the simple showincal property. */
    private java.lang.Boolean showincal;

    /**
     * Simple constructor of AbstractOrganists instances.
     */
    public AbstractOrganists()
    {
    }

    /**
     * Constructor of AbstractOrganists instances given a simple primary key.
     * @param username
     */
    public AbstractOrganists(java.lang.String username)
    {
        this.setUsername(username);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.String
     */
    public java.lang.String getUsername()
    {
        return username;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param username
     */
    public void setUsername(java.lang.String username)
    {
        this.hashValue = 0;
        this.username = username;
    }

    /**
     * Return the value of the nickname column.
     * @return java.lang.String
     */
    public java.lang.String getNickname()
    {
        return this.nickname;
    }

    /**
     * Set the value of the nickname column.
     * @param nickname
     */
    public void setNickname(java.lang.String nickname)
    {
        this.nickname = nickname;
    }

    /**
     * Return the value of the fullname column.
     * @return java.lang.String
     */
    public java.lang.String getFullname()
    {
        return this.fullname;
    }

    /**
     * Set the value of the fullname column.
     * @param fullname
     */
    public void setFullname(java.lang.String fullname)
    {
        this.fullname = fullname;
    }

    /**
     * Return the value of the details column.
     * @return java.lang.String
     */
    public java.lang.String getDetails()
    {
        return this.details;
    }

    /**
     * Set the value of the details column.
     * @param details
     */
    public void setDetails(java.lang.String details)
    {
        this.details = details;
    }

    /**
     * Return the value of the availsat column.
     * @return java.lang.Byte
     */
    public java.lang.Boolean getAvailsat()
    {
        return this.availsat;
    }

    /**
     * Return the value of the showincal column.
     * @return java.lang.Boolean
     */
    public java.lang.Boolean getShowincal()
    {
    	return this.showincal;
    }
    
    /**
     * Set the value of the availsat column.
     * @param availsat
     */
    public void setAvailsat(java.lang.Boolean availsat)
    {
        this.availsat = availsat;
    }

    /**
     * Return the value of the availsun column.
     * @return java.lang.Byte
     */
    public java.lang.Boolean getAvailsun()
    {
        return this.availsun;
    }

    /**
     * Set the value of the availsun column.
     * @param availsun
     */
    public void setAvailsun(java.lang.Boolean availsun) {
        this.availsun = availsun;
    }

    /**
     * Return the value of the travel column.
     * @return java.lang.String
     */
    public java.lang.String getTravel()
    {
        return this.travel;
    }

    /**
     * Set the value of the travel column.
     * @param travel
     */
    public void setTravel(java.lang.String travel)
    {
        this.travel = travel;
    }

    /**
     * Return the value of the wedfun column.
     * @return java.lang.String
     */
    public java.lang.String getWedfun()
    {
        return this.wedfun;
    }

    /**
     * Set the value of the wedfun column.
     * @param wedfun
     */
    public void setWedfun(java.lang.String wedfun)
    {
        this.wedfun = wedfun;
    }

    /**
     * Return the value of the available column.
     * @return java.lang.Byte
     */
    public java.lang.Boolean getAvailable()
    {
        return this.available;
    }

    /**
     * Set the value of the available column.
     * @param available
     */
    public void setAvailable(java.lang.Boolean available)
    {
        this.available = available;
    }

    /**
     * Set the value of the showincal column.
     * @param showincal
     */
    public void setShowincal(java.lang.Boolean showincal)
    {
    	this.showincal = showincal;
    }
    
    /**
     * Return the value of the username collection.
     * @return Email
     */
    public java.util.Set getEmailSet()
    {
        return this.emailSet;
    }

    /**
     * Set the value of the username collection.
     * @param emailSet
     */
    public void setEmailSet(java.util.Set emailSet)
    {
        this.emailSet = emailSet;
    }

    /**
     * Return the value of the username collection.
     * @return Phone
     */
    public java.util.Set getPhoneSet()
    {
        return this.phoneSet;
    }

    /**
     * Set the value of the username collection.
     * @param phoneSet
     */
    public void setPhoneSet(java.util.Set phoneSet)
    {
        this.phoneSet = phoneSet;
    }

    /**
     * Return the value of the username collection.
     * @return Schedules
     */
    public java.util.Set getSchedulesSet()
    {
        return this.schedulesSet;
    }

    /**
     * Set the value of the username collection.
     * @param schedulesSet
     */
    public void setSchedulesSet(java.util.Set schedulesSet)
    {
        this.schedulesSet = schedulesSet;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Organists))
            return false;
        Organists that = (Organists) rhs;
        if (this.getUsername() == null || that.getUsername() == null)
            return false;
        return (this.getUsername().equals(that.getUsername()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int usernameValue = this.getUsername() == null ? 0 : this.getUsername().hashCode();
            result = result * 37 + usernameValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
