package org.jmanderson.subbing.hibernate;



/**
 * AbstractLocation2 generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractLocation2  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Integer locationid;
     private String username;
     private String notes;


    // Constructors

    /** default constructor */
    public AbstractLocation2() {
    }

	/** minimal constructor */
    public AbstractLocation2(Integer location, String username) {
        this.locationid = location;
        this.username = username;
    }
    
    /** full constructor */
    public AbstractLocation2(Integer location, String username, String notes) {
        this.locationid = location;
        this.username = username;
        this.notes = notes;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getLocationid() {
        return this.locationid;
    }
    
    public void setLocationid(Integer location) {
        this.locationid = location;
    }

    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
   








}