/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Sep 09 17:44:18 EDT 2005 by MyEclipse Hibernate Tool.
 */
package org.jmanderson.subbing.hibernate;

import java.io.Serializable;

/**
 * A class that represents a row in the location table. 
 * You can customize the behavior of this class by editing the class, {@link Location()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractLocation 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Integer id;

    /** The value of the schedulesSet one-to-many association. */
    private java.util.Set schedulesSet;

    /** The value of the simple name property. */
    private java.lang.String name;

    /** The value of the simple address property. */
    private java.lang.String address;

    /** The value of the simple city property. */
    private java.lang.String city;

    /** The value of the simple state property. */
    private java.lang.String state;

    /** The value of the simple notes property. */
    private java.lang.String notes;

    private java.lang.Integer zip;
    
    /**
     * Simple constructor of AbstractLocation instances.
     */
    public AbstractLocation()
    {
    }

    /**
     * Constructor of AbstractLocation instances given a simple primary key.
     * @param id
     */
    public AbstractLocation(java.lang.Integer id)
    {
        this.setId(id);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Integer
     */
    public java.lang.Integer getId()
    {
        return id;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param id
     */
    public void setId(java.lang.Integer id)
    {
        this.hashValue = 0;
        this.id = id;
    }

    /**
     * Return the value of the name column.
     * @return java.lang.String
     */
    public java.lang.String getName()
    {
        return this.name;
    }

    /**
     * Set the value of the name column.
     * @param name
     */
    public void setName(java.lang.String name)
    {
        this.name = name;
    }

    /**
     * Return the value of the address column.
     * @return java.lang.String
     */
    public java.lang.String getAddress()
    {
        return this.address;
    }

    /**
     * Set the value of the address column.
     * @param address
     */
    public void setAddress(java.lang.String address)
    {
        this.address = address;
    }

    /**
     * Return the value of the city column.
     * @return java.lang.String
     */
    public java.lang.String getCity()
    {
        return this.city;
    }

    /**
     * Set the value of the city column.
     * @param city
     */
    public void setCity(java.lang.String city)
    {
        this.city = city;
    }

    /**
     * Return the value of the state column.
     * @return java.lang.String
     */
    public java.lang.String getState()
    {
        return this.state;
    }

    /**
     * Set the value of the state column.
     * @param state
     */
    public void setState(java.lang.String state)
    {
        this.state = state;
    }

    /**
     * Return the value of the notes column.
     * @return java.lang.String
     */
    public java.lang.String getNotes()
    {
        return this.notes;
    }

    /**
     * Set the value of the notes column.
     * @param notes
     */
    public void setNotes(java.lang.String notes)
    {
        this.notes = notes;
    }

    public void setZip(java.lang.Integer zip) {
    	this.zip = zip;
    }
    
    public java.lang.Integer getZip() {
    	return zip;
    }
    
    /**
     * Return the value of the locationid collection.
     * @return Schedules
     */
    public java.util.Set getSchedulesSet()
    {
        return this.schedulesSet;
    }

    /**
     * Set the value of the locationid collection.
     * @param schedulesSet
     */
    public void setSchedulesSet(java.util.Set schedulesSet)
    {
        this.schedulesSet = schedulesSet;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Location))
            return false;
        Location that = (Location) rhs;
        if (this.getId() == null || that.getId() == null)
            return false;
        return (this.getId().equals(that.getId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int idValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + idValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
