/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Sep 09 17:46:39 EDT 2005 by MyEclipse Hibernate Tool.
 */
package org.jmanderson.subbing.hibernate;

import java.io.Serializable;
import java.util.Date;

/**
 * A class that represents a row in the schedules table. 
 * You can customize the behavior of this class by editing the class, {@link Schedules()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractSchedules 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Integer id;

    /** The value of the location association. */
    private Location location;

    /** The value of the organists association. */
    private Organists organists;

    /** The value of the simple year property. */
    private java.lang.Integer year;

    /** The value of the simple month property. */
    private java.lang.Integer month;

    /** The value of the simple day property. */
    private java.lang.Integer day;

    /** The value of the simple tentative property. */
    private java.lang.Boolean tentative;

    /** The value of the simple notes property. */
    private java.lang.String notes;

    /** The value of the simple played property. */
    private java.lang.String played;

    private java.lang.Boolean holiday;
    
    private java.lang.String service_time;
    
    private java.lang.Boolean unavailable;
    
    /**
     * Simple constructor of AbstractSchedules instances.
     */
    public AbstractSchedules()
    {
    }

    /**
     * Constructor of AbstractSchedules instances given a simple primary key.
     * @param id
     */
    public AbstractSchedules(java.lang.Integer id)
    {
        this.setId(id);
        this.setNotes("");
        this.setPlayed("");
        this.setService_time("");
        this.setTentative(Boolean.FALSE);
        this.setUnavailable(Boolean.FALSE);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Integer
     */
    public java.lang.Integer getId()
    {
        return id;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param id
     */
    public void setId(java.lang.Integer id)
    {
        this.hashValue = 0;
        this.id = id;
    }

    /**
     * Return the value of the year column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getYear()
    {
        return this.year;
    }

    /**
     * Set the value of the year column.
     * @param year
     */
    public void setYear(java.lang.Integer year)
    {
        this.year = year;
    }

    /**
     * Return the value of the month column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getMonth()
    {
        return this.month;
    }

    /**
     * Set the value of the month column.
     * @param month
     */
    public void setMonth(java.lang.Integer month)
    {
        this.month = month;
    }

    /**
     * Return the value of the day column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getDay()
    {
        return this.day;
    }

    /**
     * Set the value of the day column.
     * @param day
     */
    public void setDay(java.lang.Integer day)
    {
        this.day = day;
    }

    /**
     * Return the value of the username column.
     * @return Organists
     */
    public Organists getOrganists()
    {
        return this.organists;
    }

    /**
     * Set the value of the username column.
     * @param organists
     */
    public void setOrganists(Organists organists)
    {
        this.organists = organists;
    }

    /**
     * Return the value of the locationid column.
     * @return Location
     */
    public Location getLocation()
    {
        return this.location;
    }

    /**
     * Set the value of the locationid column.
     * @param location
     */
    public void setLocation(Location location)
    {
        this.location = location;
    }

    /**
     * Return the value of the tentative column.
     * @return java.lang.Byte
     */
    public java.lang.Boolean getTentative()
    {
        return this.tentative;
    }

    /**
     * Set the value of the tentative column.
     * @param tentative
     */
    public void setTentative(java.lang.Boolean tentative)
    {
        this.tentative = tentative;
    }

    public java.lang.Boolean getHoliday() {
    	return this.holiday;
    }
    
    public void setHoliday(java.lang.Boolean holiday) {
    	this.holiday = holiday;
    }
    
    public java.lang.String getService_time() {
    	return this.service_time;
    }
    
    public void setService_time(java.lang.String service_time) {
    	this.service_time = service_time;
    }
    
    public java.lang.Boolean getUnavailable() {
    	return this.unavailable;
    }
    
    public void setUnavailable(java.lang.Boolean unavailable) {
    	this.unavailable = unavailable;
    }
    
    /**
     * Return the value of the notes column.
     * @return java.lang.String
     */
    public java.lang.String getNotes()
    {
        return this.notes;
    }

    /**
     * Set the value of the notes column.
     * @param notes
     */
    public void setNotes(java.lang.String notes)
    {
        this.notes = notes;
    }

    /**
     * Return the value of the played column.
     * @return java.lang.String
     */
    public java.lang.String getPlayed()
    {
        return this.played;
    }

    /**
     * Set the value of the played column.
     * @param played
     */
    public void setPlayed(java.lang.String played)
    {
        this.played = played;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Schedules))
            return false;
        Schedules that = (Schedules) rhs;
        if (this.getId() == null || that.getId() == null)
            return false;
        return (this.getId().equals(that.getId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int idValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + idValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
