package org.jmanderson.subbing.hibernate;
// Generated by MyEclipse - Hibernate Tools



/**
 * Location2 generated by MyEclipse - Hibernate Tools
 */
public class Location2 extends AbstractLocation2 implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Location2() {
    }

	/** minimal constructor */
    public Location2(Integer location, String username) {
        super(location, username);        
    }
    
    /** full constructor */
    public Location2(Integer location, String username, String notes) {
        super(location, username, notes);        
    }
   
}
